import React from 'react';
import * as LucideIcons from 'lucide-react';

type LucideIconComponent = React.ComponentType<{ size?: number; strokeWidth?: number; className?: string }>;

/**
 * Map of common kebab-case icon names to their PascalCase Lucide equivalents.
 * Covers icon names commonly generated by the AI prop injector.
 */
const icons = LucideIcons as unknown as Record<string, LucideIconComponent>;

const ICON_NAME_MAP: Record<string, string> = {
  // Education / Business
  'graduation-cap': 'GraduationCap',
  'hand-shake': 'Handshake',
  'handshake': 'Handshake',
  'light-bulb': 'Lightbulb',
  'lightbulb': 'Lightbulb',

  // Communication
  'phone': 'Phone',
  'phone-call': 'PhoneCall',
  'mail': 'Mail',
  'message-circle': 'MessageCircle',
  'message-square': 'MessageSquare',
  'send': 'Send',
  'inbox': 'Inbox',

  // Location
  'location': 'MapPin',
  'location-pin': 'MapPin',
  'map-pin': 'MapPin',
  'map': 'Map',
  'globe': 'Globe',
  'building': 'Building2',
  'building-2': 'Building2',

  // Actions
  'check': 'Check',
  'check-circle': 'CheckCircle',
  'check-circle-2': 'CheckCircle2',
  'check-mark': 'Check',
  'x': 'X',
  'x-circle': 'XCircle',
  'plus': 'Plus',
  'plus-circle': 'PlusCircle',
  'minus': 'Minus',
  'arrow-right': 'ArrowRight',
  'arrow-left': 'ArrowLeft',
  'arrow-up': 'ArrowUp',
  'arrow-down': 'ArrowDown',
  'chevron-right': 'ChevronRight',
  'chevron-left': 'ChevronLeft',
  'chevron-down': 'ChevronDown',
  'chevron-up': 'ChevronUp',

  // UI Elements
  'star': 'Star',
  'star-half': 'StarHalf',
  'heart': 'Heart',
  'bookmark': 'Bookmark',
  'flag': 'Flag',
  'tag': 'Tag',
  'tags': 'Tags',
  'label': 'Label',

  // Layout
  'grid': 'LayoutGrid',
  'layout-grid': 'LayoutGrid',
  'list': 'List',
  'layout-list': 'LayoutList',
  'layout': 'Layout',
  'sidebar': 'PanelLeft',
  'menu': 'Menu',
  'more-horizontal': 'MoreHorizontal',
  'more-vertical': 'MoreVertical',

  // Media
  'image': 'Image',
  'camera': 'Camera',
  'video': 'Video',
  'play': 'Play',
  'pause': 'Pause',
  'music': 'Music',

  // Files
  'file': 'File',
  'file-text': 'FileText',
  'folder': 'Folder',
  'download': 'Download',
  'upload': 'Upload',
  'clipboard': 'Clipboard',

  // Time
  'clock': 'Clock',
  'calendar': 'Calendar',
  'timer': 'Timer',
  'schedule': 'CalendarClock',

  // Stats
  'bar-chart': 'BarChart3',
  'bar-chart-3': 'BarChart3',
  'pie-chart': 'PieChart',
  'trending-up': 'TrendingUp',
  'trending-down': 'TrendingDown',
  'activity': 'Activity',

  // Misc
  'search': 'Search',
  'settings': 'Settings',
  'bell': 'Bell',
  'notification': 'Bell',
  'lock': 'Lock',
  'unlock': 'Unlock',
  'shield': 'Shield',
  'eye': 'Eye',
  'eye-off': 'EyeOff',
  'zap': 'Zap',
  'bolt': 'Zap',
  'lightning': 'Zap',
  'rocket': 'Rocket',
  'target': 'Target',
  'compass': 'Compass',
  'anchor': 'Anchor',
  'coffee': 'Coffee',
  'award': 'Award',
  'trophy': 'Trophy',
  'crown': 'Crown',
  'gem': 'Gem',
  'diamond': 'Diamond',
  'circle': 'Circle',
  'square': 'Square',
  'triangle': 'Triangle',
  'hexagon': 'Hexagon',
  'octagon': 'Octagon',

  // Tech
  'code': 'Code',
  'terminal': 'Terminal',
  'database': 'Database',
  'server': 'Server',
  'cloud': 'Cloud',
  'wifi': 'Wifi',
  'bluetooth': 'Bluetooth',
  'link': 'Link',
  'external-link': 'ExternalLink',

  // Users
  'user': 'User',
  'users': 'Users',
  'user-plus': 'UserPlus',
  'user-minus': 'UserMinus',
  'user-check': 'UserCheck',
  'group': 'Users',
  'team': 'Users',
  'people': 'Users',

  // Business
  'briefcase': 'Briefcase',
  'suitcase': 'Briefcase',
  'wallet': 'Wallet',
  'credit-card': 'CreditCard',
  'dollar-sign': 'DollarSign',
  'banknote': 'Banknote',
  'shopping-cart': 'ShoppingCart',
  'cart': 'ShoppingCart',
  'store': 'Store',
  'package': 'Package',
  'box': 'Box',
  'truck': 'Truck',
  'delivery': 'Truck',

  // Communication / Social
  'share': 'Share2',
  'share-2': 'Share2',
  'thumbs-up': 'ThumbsUp',
  'thumbs-down': 'ThumbsDown',
  'smile': 'Smile',
  'frown': 'Frown',
  'quote': 'Quote',

  // Design
  'palette': 'Palette',
  'paintbrush': 'Paintbrush',
  'pen': 'Pen',
  'pencil': 'Pencil',
  'edit': 'Pencil',
  'trash': 'Trash2',
  'trash-2': 'Trash2',
  'copy': 'Copy',
  'scissors': 'Scissors',
  'ruler': 'Ruler',

  // Misc Business
  'book-open': 'BookOpen',
  'book': 'BookOpen',
  'graduation': 'GraduationCap',
  'certificate': 'Award',
  'diploma': 'Award',
  'presentation': 'Presentation',
  'microscope': 'Microscope',
  'flask': 'FlaskConical',
  'flask-conical': 'FlaskConical',
  'atom': 'Atom',
  'brain': 'Brain',
  'cpu': 'Cpu',
  'chip': 'Cpu',
  'monitor': 'Monitor',
  'smartphone': 'Smartphone',
  'tablet': 'Tablet',
  'laptop': 'Laptop',
  'desktop': 'Monitor',
};

/**
 * Try to resolve a string icon name to a Lucide React component.
 *
 * Handles multiple naming conventions:
 * - kebab-case: "graduation-cap"
 * - camelCase: "graduationCap"
 * - PascalCase: "GraduationCap"
 * - spaces: "graduation cap"
 *
 * @param name - The icon name string from AI-generated props
 * @returns A Lucide React component, or null if not found
 */
export function resolveIcon(name: string | null | undefined): React.ReactNode {
  if (!name || typeof name !== 'string') return null;

  const trimmed = name.trim();
  if (!trimmed) return null;

  // 1. Direct lookup in our curated map (kebab-case)
  const mappedName = ICON_NAME_MAP[trimmed.toLowerCase()];
  if (mappedName) {
    const IconComponent = icons[mappedName];
    if (IconComponent) {
      return React.createElement(IconComponent, { size: 24, strokeWidth: 1.5 });
    }
  }

  // 2. Try PascalCase directly (e.g., "GraduationCap")
  const pascalName = trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
  const DirectComponent = icons[pascalName];
  if (DirectComponent) {
    return React.createElement(DirectComponent, { size: 24, strokeWidth: 1.5 });
  }

  // 3. Convert kebab-case to PascalCase and try (e.g., "graduation-cap" → "GraduationCap")
  const fromKebab = trimmed
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
  const KebabComponent = icons[fromKebab];
  if (KebabComponent) {
    return React.createElement(KebabComponent, { size: 24, strokeWidth: 1.5 });
  }

  // 4. Convert spaces to PascalCase (e.g., "graduation cap" → "GraduationCap")
  const fromSpaces = trimmed
    .split(/\s+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
  const SpaceComponent = icons[fromSpaces];
  if (SpaceComponent) {
    return React.createElement(SpaceComponent, { size: 24, strokeWidth: 1.5 });
  }

  // 5. No match found
  console.warn(`[IconResolver] No Lucide icon found for: "${trimmed}"`);
  return null;
}

/**
 * Walk an object and resolve any string `icon` fields to React components.
 * Mutates the object in place for performance.
 *
 * Handles:
 * - Direct `icon` field: `{ icon: "check-circle" }`
 * - Nested `items` array with `icon` field: `{ items: [{ icon: "star" }] }`
 *
 * @param props - The props object to process
 * @returns The same props object with resolved icons
 */
export function resolveIconsInProps(props: Record<string, any>): Record<string, any> {
  if (!props || typeof props !== 'object') return props;

  // Resolve top-level `icon` field
  if (typeof props.icon === 'string') {
    props.icon = resolveIcon(props.icon);
  }

  // Resolve icons in common array fields
  const arrayFields = ['items', 'features', 'contactItems', 'steps', 'services', 'benefits'];
  for (const field of arrayFields) {
    if (Array.isArray(props[field])) {
      props[field] = props[field].map((item: any) => {
        if (item && typeof item === 'object' && typeof item.icon === 'string') {
          return { ...item, icon: resolveIcon(item.icon) };
        }
        return item;
      });
    }
  }

  return props;
}
