export const COMPONENT_META = {
  "hero-dynamic":   { section: "hero",         supportsImages: true,  supportsItems: false, contentLevel: "medium", priority: 11 },
  "hero-simple-dynamic": { section: "hero",    supportsImages: true,  supportsItems: false, contentLevel: "medium", priority: 12 },
  "hero-elegant-dynamic": { section: "hero",   supportsImages: true,  supportsItems: false, contentLevel: "medium", priority: 12 },
  "hero-ab":      { section: "hero",         supportsImages: true,  supportsItems: false, contentLevel: "medium", priority: 10 },
  "hero-ac":      { section: "hero",         supportsImages: true,  supportsItems: false, contentLevel: "medium", priority: 9  },
  "hero-ad":      { section: "hero",         supportsImages: true,  supportsItems: false, contentLevel: "medium", priority: 9  },
  "hero-ae":      { section: "hero",         supportsImages: true,  supportsItems: false, contentLevel: "low",    priority: 8  },
  "hero-elegant": { section: "hero",         supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 6  },
  "hero-minimal": { section: "hero",         supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 6  },
  "hero-modern":  { section: "hero",         supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 7  },
  "hero-simple":  { section: "hero",         supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 5  },
  "hero-stylish": { section: "hero",         supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 5  },

  "features- Image":    { section: "features", supportsImages: true,  supportsItems: true,  contentLevel: "medium", priority: 9  },
  "features-coursel":   { section: "features", supportsImages: true,  supportsItems: true,  contentLevel: "medium", priority: 9  },
  "features-dynamic":   { section: "features", supportsImages: true,  supportsItems: true,  contentLevel: "medium", priority: 11 },
  "features-gallery-type": { section: "features", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 9 },
  "features-grid":      { section: "features", supportsImages: true,  supportsItems: true,  contentLevel: "high",   priority: 10 },
  "features-Image-new": { section: "features", supportsImages: true,  supportsItems: false, contentLevel: "low",    priority: 7  },
  "features-slideshow": { section: "features", supportsImages: true,  supportsItems: true,  contentLevel: "medium", priority: 10 },
  "features-simple-dynamic": { section: "features", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 8 },

  "about-dynamic":      { section: "about", supportsImages: true, supportsItems: false, contentLevel: "medium", priority: 11 },
  "about-simple-dynamic": { section: "about", supportsImages: true, supportsItems: false, contentLevel: "high", priority: 12 },
  "about-two-column": { section: "about", supportsImages: true, supportsItems: false, contentLevel: "low", priority: 9 },

  "testimonials-dynamic": { section: "testimonials", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 11 },
  "testimonial-cards":    { section: "testimonials", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 9 },
  "testimonial-gradient": { section: "testimonials", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 8 },
  "testimonial-modern":   { section: "testimonials", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 8 },
  "testimonial-section4": { section: "testimonials", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 7 },
  "testimonial-section5": { section: "testimonials", supportsImages: true, supportsItems: true, contentLevel: "medium", priority: 7 },

  "navbar-elegant":  { section: "navbar", supportsImages: false, supportsItems: false, contentLevel: "low", priority: 8  },
  "navbar-gradient": { section: "navbar", supportsImages: false, supportsItems: false, contentLevel: "low", priority: 7  },
  "navbar-minimal":  { section: "navbar", supportsImages: false, supportsItems: false, contentLevel: "low", priority: 10 },
  "navbar-modern":   { section: "navbar", supportsImages: false, supportsItems: false, contentLevel: "low", priority: 9  },
  "navbar-stylish":  { section: "navbar", supportsImages: false, supportsItems: false, contentLevel: "low", priority: 7  },
  "navbar-dynamic":  { section: "navbar", supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 11 },

  "footer-corporate": { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 8 },
  "footer-elegant":   { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 8 },
  "footer-gradient":  { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 6 },
  "footer-minimal":   { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 7 },
  "footer-modern":    { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 9 },
  "footer-simple":    { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "low",    priority: 8 },
  "footer-startup":   { section: "footer", supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 7 },

  "contact-form": { section: "contact", supportsImages: false, supportsItems: false, contentLevel: "low", priority: 8 },
  "contact-split-dynamic": { section: "contact", supportsImages: false, supportsItems: false, contentLevel: "medium", priority: 10 },

  "pricing-cards":    { section: "pricing", supportsImages: false, supportsItems: true, contentLevel: "medium", priority: 9 },
  "pricing-elegant":  { section: "pricing", supportsImages: false, supportsItems: true, contentLevel: "high",   priority: 8 },
  "pricing-gradient": { section: "pricing", supportsImages: false, supportsItems: true, contentLevel: "medium", priority: 8 },
  "pricing-modern":   { section: "pricing", supportsImages: false, supportsItems: false, contentLevel: "low",   priority: 7 },
  "pricing-simple":   { section: "pricing", supportsImages: false, supportsItems: true, contentLevel: "medium", priority: 7 },
};
